# Generated by Django 4.1 on 2022-08-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=40)),
                ('patente', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioHora', models.FloatField(max_length=40)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_egreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=40)),
                ('patente', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
